Release/add documentation
IslasGECI/misctools pull request #20
Opened 2021-07-26 20:49 UTC by MaritzaB

Actualicé la documentación para instalar los schemas del `geci-validate` y también agregué _Pre requisitos_ para `geci-tdp2xls`

2021-07-26 21:01 UTC, devarops requested changes

2021-07-26 21:01 UTC, devarops commented on README.md
> +$ sudo apt-get --yes install --no-install-recommends gnumeric
¿Por qué en uno usas `apt-get` y en otro `apt`?
¿Por qué en uno usas `--yes --no-install-recommends`  y en otro no?

```suggestion
sudo apt --yes install gnumeric jq
```

2021-07-26 21:01 UTC, devarops commented on Makefile
> +# Instala esquemas de JSONs
```suggestion
	# Instala esquemas de JSONs
```

2021-07-26 23:00 UTC, devarops commented
@MaritzaB ¿Por favor me lo podrías revisar?

2021-07-27 14:37 UTC, MaritzaB reviewed
@devarops se ve muy bien. Instalé las herramientas y funcionaron bien, por lo que yo le doy el VoBo.
El único detalle es que no me deja aprobar este _PR_ por que dice que soy la autora de este PR 😅 .
Tal vez @xwalls  nos puedas ayudar a darle _approve_ y _merge_ jeje.

2021-07-27 15:55 UTC, merged